replicaCount: 3

image:
  repository: us-central1-docker.pkg.dev/terraform-project-balan1/artemis/artemis
  pullPolicy: IfNotPresent
  tag: "7.0.0"




ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: prod-artemis.amazon1app.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: prod-artemis-tls
      hosts:
        - prod-artemis.amazon1app.com